#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');
const schemaPath = resolve(root, 'config', 'browser-capture-schema-v1.json');
const outputPath = resolve(here, 'generated', 'browser-capture-validator-v1.js');
const require = createRequire(resolve(root, 'packages', 'n8n-nodes-finance', 'package.json'));
const Ajv2020 = require('ajv/dist/2020').default;
const standaloneCode = require('ajv/dist/standalone').default;

const schemaBytes = readFileSync(schemaPath);
const schema = JSON.parse(schemaBytes);
const schemaSha256 = createHash('sha256').update(schemaBytes).digest('hex');
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  allowUnionTypes: true,
  code: { source: true },
});
ajv.addFormat('date', /^\d{4}-\d{2}-\d{2}$/);
ajv.addFormat('date-time', /^\d{4}-\d{2}-\d{2}T.+$/);
ajv.addFormat('uri', /^https?:\/\/[^\s]+$/);

const validate = ajv.compile(schema);
let generated = standaloneCode(ajv, validate);
const exportMatch = generated.match(/^"use strict";module\.exports = ([A-Za-z0-9_$]+);module\.exports\.default = \1;/);
if (!exportMatch) throw new Error('AJV_STANDALONE_EXPORT_SHAPE_CHANGED');
const functionName = exportMatch[1];
generated = generated.slice(exportMatch[0].length);
generated = generated.replace(
  /const ([A-Za-z0-9_$]+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/,
  `const $1 = value => {\n  let length = 0;\n  for (let index = 0; index < value.length; length += 1, index += 1) {\n    const first = value.charCodeAt(index);\n    if (first >= 0xd800 && first <= 0xdbff && index + 1 < value.length) {\n      const second = value.charCodeAt(index + 1);\n      if (second >= 0xdc00 && second <= 0xdfff) index += 1;\n    }\n  }\n  return length;\n};`,
);
if (/\brequire\s*\(/.test(generated)) throw new Error('AJV_STANDALONE_RUNTIME_REQUIRE_FORBIDDEN');

const output = [
  '// Generated by generate_browser_capture_validator.mjs; do not edit.',
  `// browser-capture-schema-v1.json sha256:${schemaSha256}`,
  generated,
  `const validateBrowserCapture = ${functionName};`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output) {
    console.error('generated browser capture validator is stale');
    process.exit(1);
  }
  console.log('generated browser capture validator is current');
} else {
  writeFileSync(outputPath, output);
}
